Repository NBCampArchive/Sikmogil, pull requests merged in 2024-07, with the labels that each got.

#110 [Feat] 운동 사진 추가 기능
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/ExerciseModel.swift
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseAlbumCell.swift
  Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/View/PhotoRecordFloatingViewController.swift
  Sikmogil/Presentation/Exercise/View/PhotoSelectViewController.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseAlbumViewModel.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseSelectionViewModel.swift
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/addPhoto.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/addPhoto.imageset/photoplus.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/photoIcon.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/photoIcon.imageset/photoButton.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/removePhoto.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/removePhoto.imageset/removePhoto.svg
  Sikmogil/Services/Network/ExerciseAPIManager.swift
Labels: 📬 API, 🎨 UIDesign, ✨ Feature

#119 [Feat] 식단 앨범 페이지네이션, 공복타이머 편의기능 추가 외
  Sikmogil/Presentation/Diet/View/AddDietMenuViewController.swift
  Sikmogil/Presentation/Diet/View/Cell/AddDietMenuTableViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietAlbumViewModel.swift
  Sikmogil/Presentation/Diet/ViewModel/addMealViewModel.swift
  Sikmogil/Resources/Assets.xcassets/Diet/fastingTimerIconFill.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/fastingTimerIconFill.imageset/fastingTimerIconFill.png
  Sikmogil/Resources/Assets.xcassets/Diet/fastingTimerIconFill.imageset/fastingTimerIconFill.svg
Labels: ✨ Feature

#120 [Design] 사진 앨범 UI
  Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/View/PhotoSelectViewController.swift
  Sikmogil/Services/Network/ExerciseAPIManager.swift
Labels: 🎨 UIDesign

#123 [Feat] 식단 앨범 상세보기, 삭제기능
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Diet/View/Cell/DietAlbumCollectionViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietPhotoSelectViewController.swift
Labels: ✨ Feature

#124 [Design] 디자인 디테일 수정, [Feat] 앨범 날짜
  Sikmogil/Model/ExerciseModel.swift
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseAlbumCell.swift
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseHistoryCell.swift
  Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/View/PhotoRecordFloatingViewController.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseSelectionViewModel.swift
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/listPlusButton.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/listPlusButton.imageset/listPlusButton.svg
Labels: 🎨 UIDesign, ✨ Feature

#127 [design] 식단 ui수정
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Presentation/Diet/View/Cell/BreakfastTableViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
Labels: 🎨 UIDesign

#128 [Feat] 앨범 사진 삭제, [Fix] 운동 추가 로직 분리
  Sikmogil/Model/ExerciseModel.swift
  Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/View/PhotoSelectViewController.swift
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseAlbumViewModel.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseViewModel.swift
  Sikmogil/Services/Network/ExerciseAPIManager.swift
Labels: ✨ Feature, 🐞 BugFix

#126 [Design] 프로필 디자인 디테일 재수정
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Application/AppDelegate.swift
  Sikmogil/Presentation/Profile/View/Cell/ProfileTableViewCell.swift
  Sikmogil/Presentation/Profile/View/Cell/SettingsTableViewCell.swift
  Sikmogil/Presentation/Profile/View/EditProfileViewController.swift
  Sikmogil/Presentation/Profile/View/GoalSettingsViewController.swift
  Sikmogil/Presentation/Profile/View/ProfileTableView.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
  Sikmogil/Presentation/Profile/View/ReminderSettingsViewController.swift
  Sikmogil/Presentation/Profile/View/SettingsViewController.swift
  Sikmogil/Presentation/Profile/View/SpandrelSettingsViewController.swift
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Sikmogil/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.png
  Sikmogil/Resources/Info.plist
  Sikmogil/Views/CustomViews/CustomAlert.swift
Labels: 🎨 UIDesign

#129 [Feat] UI 디테일 수정 및 캘린더 기능 추가
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/CalendarModel.swift
  Sikmogil/Model/DailyCalendarModel.swift
  Sikmogil/Model/PostModel.swift
  Sikmogil/Presentation/Community/View/Board/View/BoardMainViewController.swift
  Sikmogil/Presentation/Community/View/Board/View/WriteViewController.swift
  Sikmogil/Presentation/Community/View/Board/ViewModel/CreatePostViewModel.swift
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Main/View/CalendarViewController.swift
  Sikmogil/Presentation/Main/View/DayViewController.swift
  Sikmogil/Presentation/Main/View/DiaryRecordFloatingViewController.swift
  Sikmogil/Presentation/Main/View/HeaderView.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Main/View/PhotoCell.swift
  Sikmogil/Presentation/Main/View/WeightRecordFloatingViewController.swift
  Sikmogil/Presentation/Main/ViewModel/CalendarViewModel.swift
  Sikmogil/Presentation/Onboarding/View/AgreementViewController.swift
  Sikmogil/Presentation/Onboarding/View/PrivacyPolicyViewController.swift
  Sikmogil/Presentation/Onboarding/View/Step1ViewController.swift
  Sikmogil/Presentation/Onboarding/View/Step2ViewController.swift
  Sikmogil/Presentation/Onboarding/View/Step3ViewController.swift
  Sikmogil/Presentation/Profile/View/EditProfileViewController.swift
  Sikmogil/Presentation/TabBar/BottomTabBarController.swift
  Sikmogil/Resources/Assets.xcassets/Icons/calendar.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/calendar.imageset/Vector.svg
  Sikmogil/Resources/Assets.xcassets/Icons/calendar.imageset/calendar.svg
  Sikmogil/Services/Network/CalendarAPIManager.swift
Labels: ✨ Feature

#130 [Fix] 누락 내용 PR
  Sikmogil/Model/PostModel.swift
  Sikmogil/Presentation/Community/View/Board/View/WriteViewController.swift
  Sikmogil/Presentation/Community/View/Board/ViewModel/CreatePostViewModel.swift
  Sikmogil/Services/Network/BoardAPIManager.swift
Labels: 🔥 Hotfix

#131 [Fix] 테이블 뷰 라벨 Update 누락
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
Labels: 🐞 BugFix

#132 [Fix] 중복 코드 제거 및 이미지 로딩 통일
  Sikmogil/Presentation/Main/View/DayViewController.swift
  Sikmogil/Presentation/Main/View/PhotoCell.swift
  Sikmogil/Presentation/Profile/View/EditProfileViewController.swift
Labels: 🔥 Hotfix

#133 [Fix] 프로필 수정 누락 업데이트, 앱스토어 connect 언어 수정
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Login/View/LoginViewController.swift
  Sikmogil/Presentation/Profile/View/EditProfileViewController.swift
Labels: 🔥 Hotfix

#135 [docs] README
  README.md
Labels: 📃 Docs

#136 [Feat] 게시글 작성, 리스트 유지보수
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Model/BoardListResponseModel.swift
  Sikmogil/Model/PostModel.swift
  Sikmogil/Presentation/Community/View/Board/View/BoardListCell.swift
  Sikmogil/Presentation/Community/View/Board/View/BoardMainViewController.swift
  Sikmogil/Presentation/Community/View/Board/View/WriteViewController.swift
  Sikmogil/Presentation/Community/View/Board/ViewModel/BoardListViewModel.swift
  Sikmogil/Presentation/Community/View/Board/ViewModel/CreatePostViewModel.swift
  Sikmogil/Presentation/Community/View/CommunityNavigationViewController.swift
  Sikmogil/Services/Network/BoardAPIManager.swift
Labels: 📬 API, ✨ Feature

#142 [Feat] 식사추가 메뉴 수기입력 기능 추가
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/FoodDbModel.swift
  Sikmogil/Presentation/Diet/View/AddDietMenuBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/AddDietMenuViewController.swift
  Sikmogil/Services/Network/FoodDbAPIManager.swift
Labels: ✨ Feature, 🐞 BugFix

#143 [Feat] 운동 검색 화면, 직접 추가
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseItemCell.swift
  Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
  Sikmogil/Presentation/Exercise/View/ExercisePhotoViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSearchViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/FloatingPanel/CustomExerciseInputViewController.swift
  Sikmogil/Presentation/Exercise/View/FloatingPanel/PhotoRecordViewController.swift
  Sikmogil/Utills/Extensions/UIViewControllerExtension.swift
Labels: ✨ Feature
