Repository NBCampArchive/Sikmogil, pull requests merged in 2024-06, with the labels that each got.

#4 Main Branch 최신화
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Example/View/ViewController.swift
  Sikmogil/Utills/Extensions/UIViewExtensions.swift
  Sikmogil/Utills/Helpers/DateHelper.swift
  Sikmogil/Views/CustomViews/CircularProgressBar.swift
  Sikmogil/Views/CustomViews/CustomCircularProgressBar.swift
Labels: ✨ Feature

#6 [Feat] TabBarController 제작 및 Asset 추가
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Application/SceneDelegate.swift
  Sikmogil/Presentation/TabBar/BottomTabBarController.swift
  Sikmogil/Resources/Assets.xcassets/Colors/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appBlack.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appDarkGray.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appGreen.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appLightGray.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appPurple.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appSkyBlue.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Colors/appYellow.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/addPost.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/addPost.imageset/addPost.svg
  Sikmogil/Resources/Assets.xcassets/Icons/calendar.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/calendar.imageset/calendar.svg
  Sikmogil/Resources/Assets.xcassets/Icons/communication.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/communication.imageset/communication.svg
  Sikmogil/Resources/Assets.xcassets/Icons/diet.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/diet.imageset/diet.svg
  Sikmogil/Resources/Assets.xcassets/Icons/exercise.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/exercise.imageset/exercise.svg
  Sikmogil/Resources/Assets.xcassets/Icons/home.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/home.imageset/home.svg
  Sikmogil/Resources/Assets.xcassets/Icons/profile.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/profile.imageset/profile.svg
  Sikmogil/Resources/Assets.xcassets/Icons/search.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/search.imageset/search.svg
  Sikmogil/Resources/Assets.xcassets/Icons/setting.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/setting.imageset/setting.svg
  Sikmogil/Resources/Assets.xcassets/Icons/timer.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/timer.imageset/timer.svg
  Sikmogil/Resources/Fonts/SUITE-Bold.ttf
  Sikmogil/Resources/Fonts/SUITE-ExtraBold.ttf
  Sikmogil/Resources/Fonts/SUITE-Heavy.ttf
  Sikmogil/Resources/Fonts/SUITE-Light.ttf
  Sikmogil/Resources/Fonts/SUITE-Medium.ttf
  Sikmogil/Resources/Fonts/SUITE-Regular.ttf
  Sikmogil/Resources/Fonts/SUITE-SemiBold.ttf
  Sikmogil/Resources/Info.plist
  Sikmogil/Utills/Extensions/UIColorExtension.swift
  Sikmogil/Utills/Fonts/Font.swift
Labels: 🎨 UIDesign, ✨ Feature

#12 [Feat] 소셜 로그인 및 온보딩 유저 정보 수집
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Application/AppDelegate.swift
  Sikmogil/Application/SceneDelegate.swift
  Sikmogil/Model/LoginModel.swift
  Sikmogil/Model/UserProfile.swift
  Sikmogil/Presentation/Example/View/ViewController.swift
  Sikmogil/Presentation/Login/View/LoginViewController.swift
  Sikmogil/Presentation/Login/ViewModel/LoginViewModel.swift
  Sikmogil/Presentation/Onboarding/View/OnboardingPageViewController.swift
  Sikmogil/Presentation/Onboarding/View/OnboardingProgressBar.swift
  Sikmogil/Presentation/Onboarding/View/Step1ViewController.swift
  Sikmogil/Presentation/Onboarding/View/Step2ViewController.swift
  Sikmogil/Presentation/Onboarding/View/Step3ViewController.swift
  Sikmogil/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  Sikmogil/Resources/Assets.xcassets/Icons/googleLogo.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/googleLogo.imageset/_googleLogo.svg
  Sikmogil/Resources/Info.plist
  Sikmogil/Resources/SikmogilPlist.plist
  Sikmogil/Services/Network/LoginAPIManager.swift
  Sikmogil/Services/Network/UserAPIManager.swift
  Sikmogil/Sikmogil.entitlements
  Sikmogil/Utills/Extensions/SikmogilBundle++.swift
  Sikmogil/Utills/Extensions/UIViewControllerExtension.swift
  Sikmogil/Utills/Extensions/UIViewExtensions.swift
  Sikmogil/Views/CustomViews/WaveProgressView.swift
Labels: 📬 API, 🎨 UIDesign, ✨ Feature

#13 [Design] 운동 화면 UI 초기 구성
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseHistoryCell.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/TabBar/BottomTabBarController.swift
  Sikmogil/Resources/Assets.xcassets/ButtonImages/Contents.json
  Sikmogil/Resources/Assets.xcassets/ButtonImages/pause.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/ButtonImages/pause.imageset/Start.svg
  Sikmogil/Resources/Assets.xcassets/ButtonImages/stop.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/ButtonImages/stop.imageset/stop.svg
  Sikmogil/Resources/Assets.xcassets/Images/Contents.json
  Sikmogil/Resources/Assets.xcassets/Images/active.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Images/active.imageset/active.svg
  Sikmogil/Resources/Assets.xcassets/Images/check.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Images/check.imageset/check.svg
  Sikmogil/Resources/Assets.xcassets/Images/running.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Images/running.imageset/running.svg
  Sikmogil/Resources/Assets.xcassets/Images/steps.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Images/steps.imageset/steps.svg
  Sikmogil/Utills/Extensions/Extension.swift
Labels: 🎨 UIDesign

#15 [Fix] 잃어버린 StepView 찾아오기
  Sikmogil.xcodeproj/project.pbxproj
Labels: 🔥 Hotfix

#17 Feat/#10 식단 화면 UI 초기 구성
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Diet/View/AddDietMenuViewController.swift
  Sikmogil/Presentation/Diet/View/Cell/AddDietMenuTableViewCell.swift
  Sikmogil/Presentation/Diet/View/Cell/DietAlbumCollectionViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietViewModel.swift
  Sikmogil/Presentation/TabBar/BottomTabBarController.swift
  Sikmogil/Resources/Assets.xcassets/Diet/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/addIconRound.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/addIconRound.imageset/addIconRound.svg
  Sikmogil/Resources/Assets.xcassets/Diet/addRingDuotone.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/addRingDuotone.imageset/addRingDuotone.svg
  Sikmogil/Resources/Assets.xcassets/Diet/dietIcon.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/dietIcon.imageset/dietIcon.svg
  Sikmogil/Resources/Assets.xcassets/Diet/dietIconFill.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/dietIconFill.imageset/dietIconFill.svg
  Sikmogil/Resources/Assets.xcassets/Diet/fastingTimerIconFill.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/fastingTimerIconFill.imageset/fastingTimerIconFill.png
  Sikmogil/Resources/Assets.xcassets/Diet/plusIcon.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/plusIcon.imageset/plusIcon.svg
  Sikmogil/Resources/Assets.xcassets/Diet/waterProgress.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Diet/waterProgress.imageset/waterProgress.svg
  Sikmogil/Utills/Extensions/FloatingPanelControllerStyle.swift
  Sikmogil/Utills/Extensions/UIApplication.swift
Labels: 🎨 UIDesign

#18 Feat/#8 프로필 UI
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Profile/View/Cell/AlarmTableViewCell.swift
  Sikmogil/Presentation/Profile/View/Cell/ProfileTableViewCell.swift
  Sikmogil/Presentation/Profile/View/EditProfileViewController.swift
  Sikmogil/Presentation/Profile/View/GoalSettingsViewController.swift
  Sikmogil/Presentation/Profile/View/NotificationSettingsViewController.swift
  Sikmogil/Presentation/Profile/View/ProfileInfoView.swift
  Sikmogil/Presentation/Profile/View/ProfileTableView.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
  Sikmogil/Presentation/Profile/View/ReminderSettingsViewController.swift
  Sikmogil/Presentation/TabBar/BottomTabBarController.swift
  Sikmogil/Resources/Assets.xcassets/Icons/cup.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/cup.imageset/cup.svg
  Sikmogil/Resources/Assets.xcassets/Icons/heart.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/heart.imageset/Vector.svg
  Sikmogil/Resources/Assets.xcassets/Icons/levelbar.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/levelbar.imageset/levelbar.svg
  Sikmogil/Resources/Assets.xcassets/Icons/pencilline.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/pencilline.imageset/PencilLine.svg
Labels: 🎨 UIDesign

#22 [Fix] diet proj 파일 추가
  Sikmogil.xcodeproj/project.pbxproj
Labels: 🔥 Hotfix

#25 [Fix] 잃어버린 Diet 찾기
  Sikmogil.xcodeproj/project.pbxproj
Labels: 🐞 BugFix

#27 [Fix] 사라진 Utills 하위 파일 추가
  Sikmogil.xcodeproj/project.pbxproj
Labels: 🔥 Hotfix

#21 [Feat] 로그인 로직 고도화
  Sikmogil/Application/SceneDelegate.swift
  Sikmogil/Model/LoginModel.swift
  Sikmogil/Presentation/Login/View/LoginViewController.swift
  Sikmogil/Presentation/Login/ViewModel/LoginViewModel.swift
  Sikmogil/Services/Network/LoginAPIManager.swift
  Sikmogil/Services/Network/UserAPIManager.swift
Labels: 📬 API, ✨ Feature

#34 [Feat] 운동 관련 API Manager 추가
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/ExerciseModel.swift
  Sikmogil/Services/Network/ExerciseAPIManager.swift
  Sikmogil/Services/Network/LoginAPIManager.swift
Labels: 📬 API

#35 [Feat] 식단 API, Model Update
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/DietModel.swift
  Sikmogil/Model/ExerciseModel.swift
  Sikmogil/Model/ImageModel.swift
  Sikmogil/Model/UserProfile.swift
  Sikmogil/Services/Network/DietAPIManager.swift
  Sikmogil/Services/Network/ImageAPIManager.swift
Labels: 📬 API

#31 [Design] 운동 UI 디테일 수정, [Feat] 건강 데이터 연동, 타이머 기능
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseHistoryCell.swift
  Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/TabBar/BottomTabBarController.swift
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/pause.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/pause.imageset/Start.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/stop.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/ButtonImages/stop.imageset/stop.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/active.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/active.imageset/active.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/check.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/check.imageset/check.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/running.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/running.imageset/running.svg
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/steps.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Exercise/Images/steps.imageset/steps.svg
  Sikmogil/Resources/Info.plist
  Sikmogil/Sikmogil.entitlements
  Sikmogil/Views/CustomViews/HalfCircleProgressView.swift
Labels: 🎨 UIDesign, ✨ Feature

#41 [Fix] add parameters & PackageConflict
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Services/Network/DietAPIManager.swift
Labels: 🐞 BugFix

#37 [Feat] 식단 앨범 기능추가, 물마시기 수정 #28
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Application/SceneDelegate.swift
  Sikmogil/Model/SavedDietImage.swift
  Sikmogil/Model/UserProfile.swift
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Diet/View/AddDietMenuViewController.swift
  Sikmogil/Presentation/Diet/View/Cell/AddDietMenuTableViewCell.swift
  Sikmogil/Presentation/Diet/View/Cell/DietAlbumCollectionViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietAlbumViewModel.swift
  Sikmogil/Utills/Extensions/FloatingPanelControllerStyle.swift
Labels: ✨ Feature

#44 [feat] 물마시기 프로그래스바 / 공복타이머 기능구현
  Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietViewModel.swift
Labels: ✨ Feature

#39 [Feat] Calendar API 추가
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Application/SceneDelegate.swift
  Sikmogil/Model/CalendarModel.swift
  Sikmogil/Services/Network/CalendarAPIManager.swift
Labels: 📬 API

#46 [Feat] 캘린더 패널 수정, API 코드 수정
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Main/View/CalendarViewController.swift
  Sikmogil/Presentation/Main/View/DiaryRecordFloatingViewController.swift
  Sikmogil/Services/Network/DietAPIManager.swift
  Sikmogil/Services/Network/UserAPIManager.swift
  Sikmogil/Utills/Extensions/UIViewControllerExtension.swift
  Sikmogil/Utills/Helpers/FloatingPannelStyleHelper.swift
Labels: 🔥 Hotfix, ✨ Feature

#47 [Feat] 식단 식품영양성분DB정보 API 연결
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/FoodDbModel.swift
  Sikmogil/Presentation/Diet/View/AddDietMenuViewController.swift
  Sikmogil/Presentation/Diet/View/Cell/AddDietMenuTableViewCell.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Resources/Info.plist
  Sikmogil/Resources/SikmogilPlist.plist
  Sikmogil/Services/Network/FoodDbAPIManager.swift
  Sikmogil/Utills/Extensions/SikmogilBundle++.swift
Labels: 📬 API, ✨ Feature

#48 [Feat] Exercise API Test, 공공 헬스케어 운동 API 추가, 화면 로직
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Exercise/View/APITestViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseViewModel.swift
  Sikmogil/Resources/SikmogilPlist.plist
  Sikmogil/Services/Network/ExerciseAPIManager.swift
  Sikmogil/Services/Network/ExerciseCategoryAPIManager.swift
  Sikmogil/Utills/Extensions/Double.swift
  Sikmogil/Utills/Extensions/Extension.swift
  Sikmogil/Utills/Extensions/SikmogilBundle++.swift
  Sikmogil/Utills/Extensions/UILabel.swift
Labels: 📬 API, ✨ Feature

#49 [Feat] Custom Calendar
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil.xcodeproj/xcshareddata/xcschemes/Sikmogil.xcscheme
  Sikmogil/Model/CalendarModel.swift
  Sikmogil/Model/UserProfile.swift
  Sikmogil/Presentation/Main/View/CalendarCell.swift
  Sikmogil/Presentation/Main/View/CalendarViewController.swift
  Sikmogil/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  Sikmogil/Services/Network/UserAPIManager.swift
Labels: ✨ Feature, 🔧 Chore

#51 [Fix] User 정보 출력 모델 및 API Func 수정
  Sikmogil/Model/UserProfile.swift
  Sikmogil/Services/Network/UserAPIManager.swift
Labels: 🔥 Hotfix

#55 [Feat] 캘린더, 목표화면 API 적용
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Application/AppDelegate.swift
  Sikmogil/Model/CalendarModel.swift
  Sikmogil/Model/TargetModel.swift
  Sikmogil/Presentation/Main/View/CalendarCell.swift
  Sikmogil/Presentation/Main/View/CalendarViewController.swift
  Sikmogil/Presentation/Main/View/DayViewController.swift
  Sikmogil/Presentation/Main/View/DiaryRecordFloatingViewController.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Main/View/WeightRecordFloatingViewController.swift
  Sikmogil/Presentation/Main/ViewModel/CalendarViewModel.swift
  Sikmogil/Presentation/Main/ViewModel/MainViewModel.swift
  Sikmogil/Services/Network/CalendarAPIManager.swift
  Sikmogil/Services/Network/LoginAPIManager.swift
Labels: 📬 API, ✨ Feature

#59 [Feat] User Onboarding 정보 업데이트
  Sikmogil/Application/SceneDelegate.swift
  Sikmogil/Model/UserProfile.swift
  Sikmogil/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
  Sikmogil/Services/Network/UserAPIManager.swift
Labels: ✨ Feature

#58 [Feat] 운동 데이터 로직 및 API 연결]
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Exercise/View/APITestViewController.swift
  Sikmogil/Presentation/Exercise/View/Cell/ExerciseHistoryCell.swift
  Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseSelectionViewModel.swift
  Sikmogil/Presentation/Exercise/ViewModel/ExerciseViewModel.swift
Labels: 📬 API, ✨ Feature

#57 [Feat] 식단 API연결
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Diet/View/DietAPITest.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietViewModel.swift
  Sikmogil/Presentation/Diet/ViewModel/WaterViewModel.swift
  Sikmogil/Presentation/Diet/ViewModel/addMealViewModel.swift
  Sikmogil/Resources/SikmogilPlist.plist
  Sikmogil/Services/Network/DietAPIManager.swift
Labels: 📬 API, ✨ Feature

#92 [Fix] 목표기간 성별 데이터 오류 수정
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
Labels: 🔥 Hotfix

#94 [Fix] 걸음수 업데이트 수정
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
Labels: 🐞 BugFix

#96 [Fix] 목표 화면 퍼센트 뷰, 스크롤 영역 수정
  Sikmogil/Presentation/Main/View/MainViewController.swift
Labels: 🔥 Hotfix

#97 [Deploy] 1차 배포 리젝 사유 및 일부 기능 수정 업데이트
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
Labels: 🌏 Deploy

#101 [Feat] 화면 전환 에니메이션 수정, API RequestInspector 추가, 토큰 저장소 분리
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Login/View/LoginViewController.swift
  Sikmogil/Presentation/Login/ViewModel/LoginViewModel.swift
  Sikmogil/Presentation/Onboarding/View/PermissionViewController.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
  Sikmogil/Presentation/Splash/SplashViewController.swift
  Sikmogil/Services/Network/AuthInterceptor.swift
  Sikmogil/Services/Network/CalendarAPIManager.swift
  Sikmogil/Services/Network/DietAPIManager.swift
  Sikmogil/Services/Network/ExerciseAPIManager.swift
  Sikmogil/Services/Network/ImageAPIManager.swift
  Sikmogil/Services/Network/LoginAPIManager.swift
  Sikmogil/Services/Network/ProfileAPIManager.swift
  Sikmogil/Services/Network/UserAPIManager.swift
  Sikmogil/Services/PersistentStorage/TokenStorage.swift
Labels: ✨ Feature

#100 [Feat/Design] 식단 앨범 api 연결 / 다이어트 바텀시트 ui 수정
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/DietModel.swift
  Sikmogil/Model/SavedDietImage.swift
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Diet/View/Cell/BreakfastTableViewCell.swift
  Sikmogil/Presentation/Diet/View/Cell/DinnerTableViewCell.swift
  Sikmogil/Presentation/Diet/View/Cell/LunchTableViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietAlbumViewModel.swift
  Sikmogil/Presentation/Diet/ViewModel/addMealViewModel.swift
  Sikmogil/Services/Network/DietAPIManager.swift
  Sikmogil/Services/Network/ImageAPIManager.swift
Labels: 📬 API, ✨ Feature

#103 [Fix] 플로팅 패널, 목표기간 수정
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Main/ViewModel/MainViewModel.swift
  Sikmogil/Services/Network/ImageAPIManager.swift
Labels: 🔨 Refactor

#104 [Deploy] 1차 배포 내용 수정
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Model/DietModel.swift
  Sikmogil/Model/SavedDietImage.swift
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Diet/View/Cell/BreakfastTableViewCell.swift
  Sikmogil/Presentation/Diet/View/Cell/DinnerTableViewCell.swift
  Sikmogil/Presentation/Diet/View/Cell/LunchTableViewCell.swift
  Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
  Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Diet/ViewModel/DietAlbumViewModel.swift
  Sikmogil/Presentation/Diet/ViewModel/addMealViewModel.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Main/ViewModel/MainViewModel.swift
  Sikmogil/Services/Network/DietAPIManager.swift
  Sikmogil/Services/Network/ImageAPIManager.swift
Labels: 🌏 Deploy

#106 [Fix] 목표 수정 화면 캘린더 선택 제한, 키보드 이벤트, 첫 가입시 체중 목표까지 오류수정
  Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Profile/View/GoalSettingsViewController.swift
  Sikmogil/Presentation/Profile/View/NotificationSettingsViewController.swift
Labels: 🔥 Hotfix

#109 [Fix] 1차 리젝 내용 일부 수정
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Onboarding/View/PermissionViewController.swift
Labels: 🔥 Hotfix, 🔨 Refactor

#98 [Feat] 프로필 설정 UI 수정
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Onboarding/View/PrivacyPolicyViewController.swift
  Sikmogil/Presentation/Profile/View/Cell/SettingsTableViewCell.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
  Sikmogil/Presentation/Profile/View/SettingsViewController.swift
  Sikmogil/Presentation/Profile/View/SpandrelSettingsViewController.swift
  Sikmogil/Resources/Assets.xcassets/Colors/appDeepDarkGray.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/Information.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/Information.imageset/mingcute_information-line.svg
  Sikmogil/Resources/Assets.xcassets/Icons/alarm.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/alarm.imageset/alarm-01.svg
  Sikmogil/Resources/Assets.xcassets/Icons/clock.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/clock.imageset/clock-01.svg
  Sikmogil/Resources/Assets.xcassets/Icons/key.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/key.imageset/key-02.svg
  Sikmogil/Resources/Assets.xcassets/Icons/marker.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/marker.imageset/marker-05.svg
  Sikmogil/Resources/Assets.xcassets/Icons/stopwatch.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/stopwatch.imageset/stopwatch-03.svg
  Sikmogil/Resources/Assets.xcassets/Icons/user.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/user.imageset/user-profile-03.svg
Labels: 🎨 UIDesign

#112 [Deploy] 1차 배포 리젝 사항 수정
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Onboarding/View/PrivacyPolicyViewController.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
  Sikmogil/Presentation/Profile/View/SettingsViewController.swift
  Sikmogil/Presentation/Profile/View/SpandrelSettingsViewController.swift
  Sikmogil/Presentation/Splash/SplashViewController.swift
  Sikmogil/Presentation/TabBar/CustomNavigationController.swift
  Sikmogil/Resources/Info.plist
  Sikmogil/Services/Network/UserAPIManager.swift
  Sikmogil/Utills/Helpers/NotificationHelper.swift
Labels: 🌏 Deploy, 🔥 Hotfix

#113 [Develop] 1차 배포 리젝 대응 및 수정사항 점검
  Sikmogil.xcodeproj/project.pbxproj
  Sikmogil/Presentation/Diet/View/DietMainViewController.swift
  Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
  Sikmogil/Presentation/Exercise/View/StepsViewController.swift
  Sikmogil/Presentation/Main/View/MainViewController.swift
  Sikmogil/Presentation/Onboarding/View/PermissionViewController.swift
  Sikmogil/Presentation/Onboarding/View/PrivacyPolicyViewController.swift
  Sikmogil/Presentation/Profile/View/Cell/SettingsTableViewCell.swift
  Sikmogil/Presentation/Profile/View/ProfileViewController.swift
  Sikmogil/Presentation/Profile/View/SettingsViewController.swift
  Sikmogil/Presentation/Profile/View/SpandrelSettingsViewController.swift
  Sikmogil/Presentation/Splash/SplashViewController.swift
  Sikmogil/Presentation/TabBar/CustomNavigationController.swift
  Sikmogil/Resources/Assets.xcassets/Colors/appDeepDarkGray.colorset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/Information.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/Information.imageset/mingcute_information-line.svg
  Sikmogil/Resources/Assets.xcassets/Icons/alarm.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/alarm.imageset/alarm-01.svg
  Sikmogil/Resources/Assets.xcassets/Icons/clock.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/clock.imageset/clock-01.svg
  Sikmogil/Resources/Assets.xcassets/Icons/key.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/key.imageset/key-02.svg
  Sikmogil/Resources/Assets.xcassets/Icons/marker.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/marker.imageset/marker-05.svg
  Sikmogil/Resources/Assets.xcassets/Icons/stopwatch.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/stopwatch.imageset/stopwatch-03.svg
  Sikmogil/Resources/Assets.xcassets/Icons/user.imageset/Contents.json
  Sikmogil/Resources/Assets.xcassets/Icons/user.imageset/user-profile-03.svg
  Sikmogil/Resources/Info.plist
  Sikmogil/Services/Network/UserAPIManager.swift
  Sikmogil/Utills/Helpers/NotificationHelper.swift
Labels: 🌏 Deploy

#114 [refactor] 최초 로그인 시 공복시간 14시간으로 설정
  Sikmogil/Presentation/Onboarding/View/Step3ViewController.swift
Labels: 🔥 Hotfix

#115 [refactor] 최초 로그인 시 공복시간 14시간으로 설정
  Sikmogil/Presentation/Onboarding/View/Step3ViewController.swift
Labels: 🔥 Hotfix
